> /home/neuro/Downloads/models/cacam_models/camkii/rxn_Kcam_init1/rxn_process.py(35)<module>()
-> f.write(rxn_part)
(Pdb) Traceback (most recent call last):
  File "../rxn_process.py", line 35, in <module>
    f.write(rxn_part)
  File "../rxn_process.py", line 35, in <module>
    f.write(rxn_part)
  File "/home/neuro/miniconda2/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/neuro/miniconda2/lib/python2.7/bdb.py", line 67, in dispatch_line
    self.user_line(frame)
  File "/home/neuro/miniconda2/lib/python2.7/pdb.py", line 158, in user_line
    self.interaction(frame, None)
  File "/home/neuro/miniconda2/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/home/neuro/miniconda2/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
IOError: [Errno 9] Bad file descriptor
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1033
1043
1053
1063
1073
1083
1093
1103
1113
1123
1133
1143
1153
1163
1173
1183
1193
1203
1213
1223
1233
1243
1253
1263
1273
1283
1293
1303
1313
1323
1333
1343
1353
1363
1373
1383
1393
1403
1413
1423
1433
1443
1453
1463
1523
1533
1543
1553
1563
1573
1583
1593
1603
1613
1623
1633
1643
1653
1663
1673
1683
1693
1703
1713
1723
1733
1743
1753
1763
1773
1783
1793
1803
1813
1823
1833
1843
1853
1863
1873
1883
1893
1903
1913
1923
1933
1943
1953
1963
1973
1983
1993
